- name: Remove .kube directory
  ansible.builtin.file:
    path: "~/.kube/"
    state: absent
  become: true

- name: Remove CNI network interfaces
  ansible.builtin.file:
    path: /etc/cni/net.d
    state: absent
  become: true
