- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: install ca-certificates
  apt:
    name: ca-certificates
    state: present
  become: true

- name: install curl
  apt:
    name: curl
    state: present
  become: true

- name: install gpg
  apt:
    name: gpg
    state: present
  become: true

- name: get helm release signing key
  shell: 'curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | sudo gpg --yes --dearmor -o /etc/apt/keyrings/helm-apt-keyring.gpg'
  become: true

- name: add in apt source for helm
  apt_repository:
    repo: '[signed-by=/etc/apt/keyrings/helm-apt-keyring.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ /"'
    state: present
    filename: 'kubernetes'
    update_cache: true
  become: true
