- name: enable cpuset cgroup
  shell: 'sed -i.bak "/cgroup_enable=cpuset/!s/$/ cgroup_enable=cpuset/" /boot/firmware/cmdline.txt'
  become: true

- name: enable cgroup memory
  shell: 'sed -i "/cgroup_enable=memory/!s/$/ cgroup_enable=memory/" /boot/firmware/cmdline.txt'
  become: true

- name: enable ipv4 forwarding
  shell: 'sed -i "/net.ipv4.ip_forward=1/!s/$/ net.ipv4.ip_forward=1/" /etc/sysctl.conf'
  become: true

- name: disable swap
  service:
    name: dphys-swapfile
    enabled: no
    state: stopped
  become: true