- name: enable cpuset cgroup
  shell: "sed -i.bak '/cgroup_enable=cpuset/!s/$/ cgroup_enable=cpuset/' /boot/firmware/cmdline.txt"
  become: true
  notify: reboot

- name: enable cgroup memory
  shell: "sed -i -e 's/ cgroup_memory=0//g' -e 's/ cgroup_disable=memory//g' -e '/cgroup_enable=memory/!s/$/ cgroup_enable=memory/' /boot/firmware/cmdline.txt"
  become: true
  notify: reboot

- name: enable cgroup hugetlb
  shell: "sed -i '/cgroup_enable=hugetlb/!s/$/ cgroup_enable=hugetlb/' /boot/firmware/cmdline.txt"
  become: true
  notify: reboot

- name: run handlers
  meta: flush_handlers
