- name: enable cpuset cgroup
  shell: 'sed -i.bak "/cgroup_enable=cpuset/!s/$/ cgroup_enable=cpuset/" /boot/firmware/cmdline.txt'
  become: true

- name: enable memory cgroup
  shell: 'sed -i "/cgroup_memory=1/!s/$/ cgroup_memory=1/" /boot/firmware/cmdline.txt'
  become: true

- name: enable cgroup memory
  shell: 'sed -i "/cgroup_enable=memory/!s/$/ cgroup_enable=memory/" /boot/firmware/cmdline.txt'
  become: true
