- name: create CNI directory
  file:
    path: "{{ k8s_cni_directory }}"
    state: directory

- name: "configure Calico CNI"
  template:
    src: "calico.yml.j2"
    dest: "/etc/kubernetes/calico.yml"

- name: install calico kubectl plugin
  get_url:
    url: "https://github.com/projectcalico/calico/releases/download/v{{ k8s_cni_calico_version }}/calicoctl-linux-arm64"
    mode: '0755'
    dest: "/usr/local/bin/kubectl-calico"
