- name: Cleanup after k8s reset
  ansible.builtin.include_tasks: k8s_cleanup.yml
  listen: k8s_cleanup

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true
  listen: restart_containerd
