- name: debug request
  debug:
    msg: "{{ infiscal_workspace_id }} {{ infiscal_environment }}"

- name: Retrieve secret from Infiscal
  register: raw_secret_response
  no_log: "{{ not lookup('env', 'DEBUG') | default(false) | bool }}"
  uri:
    method: GET
    url: "{{ lookup('env', 'INFISCAL_API_URL') }}/secrets/raw/{{ secret_name }}"
    headers:
      Authorization: "Bearer {{ lookup('env', 'INFISCAL_API_KEY') }}"
    body_format: json
    body:
      secretPath: "{{ secret_path | default('/') }}"
      type: "{{ secret_type | default('shared') }}"
      viewSecretValue: "{{ view_secret_value | default('true') | bool }}"
      expandSecretReferences: "{{ expand_secret_references | default('false') | bool }}"
      include_imports: "{{ include_imports | default('false') | bool }}"
      workspaceId: "{{ infiscal_workspace_id }}"
      environment: "{{ infiscal_environment }}"

- name: Set fact for secret value
  set_fact:
    secret_value: "{{ raw_secret_response.json.secretValue }}"
    cacheable: true
  when: raw_secret_response.status == 200
  no_log: "{{ not lookup('env', 'DEBUG') | default(false) | bool }}"