- name: Update apt
  apt:
    update_cache: yes
    upgrade: 'safe'
    state: latest

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname is defined

# - name: Create users and groups
#   include_tasks: configure_user_group.yml

- name: Configure patching
  include_tasks: configure_patching.yml

# - name: Configure mounting points
#   include_tasks: mount_disks.yml

- name: Create temporary directory
  file:
    path: "{{ temp_directory }}"
    state: directory
    mode: '0700'
