- name: Install common swap package
  apt:
    name: dphys-swapfile
    state: present
  become: true

- name: Ensure rpi-swap is removed
  apt:
    name: rpi-swap
    state: absent
  become: true

- name: Disable swap service
  service:
    name: dphys-swapfile
    enabled: false
    masked: true
    state: stopped
  become: true

- name: Mask swap in systemd
  systemd:
    name: dev-zram0.swap
    masked: true
  become: true

- name: Disable swap
  shell: swapoff --all
  become: true
