- name: Enable required cgroups
  ansible.builtin.include_tasks: enable_cgroup.yml
  loop:
    - cpuset
    - memory
    - hugetlb

- name: Run handlers if any cgroup settings were changed
  ansible.builtin.meta: flush_handlers
