- name: enable cpuset cgroup
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '(.*)($)'
    line: '\1 cgroup_enable=cpuset\2'
    state: present
    # backup: true
  # notify: reboot

- name: enable memory cgroup
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '(.*)($)'
    line: '\1 cgroup_enable=memory\2'
    state: present
    # backup: true
  # notify: reboot

- name: enable hugetlb cgroup
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '(.*)($)'
    line: '\1 cgroup_enable=hugetlb\2'
    state: present
    # backup: true
  # notify: reboot

# - name: run handlers if any cgroup settings were changed
#   meta: flush_handlers
