- name: enable required cgroups
  include_tasks: enable_cgroup.yml
  loop:
    - cpuset
    - memory
    - hugetlb

# - name: run handlers if any cgroup settings were changed
#   meta: flush_handlers
