- name: Create CNI directory
  ansible.builtin.file:
    path: "{{ k8s_cni_directory }}"
    state: directory

- name: Pull Calico k8s setup
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_cni_calico_version }}/manifests/calico.yaml"
    dest: "{{ k8s_cni_directory }}/calico.yml"

- name: Update calico ip pool
  ansible.builtin.replace:
    path: "{{ k8s_cni_directory }}/calico.yml"
    regexp: "{{ item.key }}"
    replace: "{{ item.value }}"
  with_items:
    - "(# )?- name: CALICO_IPV4POOL_CIDR": "- name: CALICO_IPV4POOL_CIDR"
    - "(# )?  value: \"[0-9\\./]\"": "  value: \"{{ k8s_cni_calico_ipv4pool_cidr }}\""

- name: Apply Calico CNI configuration
  ansible.builtin.command: "kubectl --kubeconfig={{ k8s_kubectl_config_path }} apply -f {{ k8s_cni_directory }}/calico.yml"
