- name: "Install docker components"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  become: true

- name: Enable and start docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Enable and start containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
    daemon_reload: true
  become: true
